name: Run PDF Merger

on:
  workflow_dispatch:

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pypdf

      - name: Run Script
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python merge_next_ias.py

      - name: Check Output File
        run: |
          ls -lh Next_IAS_GS4_Merged.pdf || echo "File not found!"

      - name: Upload Merged PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Next-IAS-GS4-Merged-PDF
          path: Next_IAS_GS4_Merged.pdf
